jwt:
  key:
    #스프링부트 마스터하고싶다
    access: 7Iqk7ZSE66eB67aA7Yq4IOuniOyKpO2EsO2VmOqzoOyLtuuLpA==
    #스프링부트 마스터하고싶다 진짜로
    refresh: 7Iqk7ZSE66eB67aA7Yq4IOuniOyKpO2EsO2VmOqzoOyLtuuLpCDsp4Tsp5zroZw=
  max-age:
    access: 1800 # 60 * 30
    refresh: 604800 # 60 * 60 * 24 * 7